### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.xuecheng-plus.com
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=VYZ87h&redirect_uri=http://www.xuecheng-plus.com



### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"authType":"password","username":"itcast","password":"111111"}


###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjZWxscGhvbmVcIjpcIjEyMzQ1XCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJlbWFpbFwiOlwiXCIsXCJpZFwiOlwiNDlcIixcIm5hbWVcIjpcInRlc3QwMlwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCIxXCIsXCJ1c2VybmFtZVwiOlwiaXRjYXN0XCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY3NzkyNDM2NCwiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiY2EzMjdmZDYtYWViNC00ZWJmLWFmNzYtOWNlNDk3OGRkM2VhIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.D3MO7PCF8ueGImvCK3J7OsCDKskbbehB1f-gkpo2lAY

###访问根据课程id查询课程接口
GET http://localhost:63040/content/course/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjZWxscGhvbmVcIjpcIjEyMzQ1XCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJlbWFpbFwiOlwiXCIsXCJpZFwiOlwiNDlcIixcIm5hbWVcIjpcInRlc3QwMlwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJpdGNhc3RcIixcInV0eXBlXCI6XCIxMDEwMDJcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc3ODY0MzUxLCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjZlNTY1MzY2LWFmN2UtNDIzMC05MWFhLTg0NTVmNWVlZDlhMCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.w-eAze2TA5-VwY-XyENGa3JR9nIisc8eYVphFYLdV6o
###访问网关
GET http://localhost:63010/content/course/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2Nzc4NDg2MjIsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImFiNjk0Y2I2LTZmZDgtNDlhZi05ODExLTUyZDNlYzc0NjkxMyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.WpaF2jTysZxhDZ6j7dsaElOioo9T-Wu6lNBlMMXcJ_g

### 密码模式
POST {{auth_host}}/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=stu1&password=111111
